version: "3.7"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379"
  db:
    image: postgres:12.2
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'clicker'
      POSTGRES_USER: 'clicker'
      POSTGRES_PASSWORD: 'clicker'
  clicker:
    build: .
    ports:
      - "8000:80"
    environment:
      POSTGRES_URL: 'postgres://clicker:clicker@db/clicker'
      REDIS_URL: 'redis'
    depends_on:
      - redis
      - db

volumes:
  db-data:
