version: "3.3"
services:
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --requirepass $REDIS_PASSWORD
    ports:
      - "6379:6379"
  db:
    image: postgres:12.2
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./.db_env
  clicker:
    build: .
    ports:
      - "8000:80"
    env_file:
      - ./.clicker_env
    depends_on:
      - redis
      - db

volumes:
  db-data:
  redis-data:
