"""empty message

Revision ID: 37a62eee5835
Revises: a0d565db90b5
Create Date: 2020-03-07 18:46:23.189064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37a62eee5835'
down_revision = 'a0d565db90b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
