"""empty message

Revision ID: 53d530d3c054
Revises: e9af5fef39e2
Create Date: 2020-03-15 09:00:19.761010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53d530d3c054'
down_revision = '8c17c134ecd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upgrade', sa.Column('multiplier', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upgrade', 'multiplier')
    # ### end Alembic commands ###
