"""empty message

Revision ID: a0d565db90b5
Revises: fad501b8fddd
Create Date: 2020-03-07 18:45:14.363786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0d565db90b5'
down_revision = 'fad501b8fddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generator', sa.Column('income_rate', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created')
    op.drop_column('generator', 'income_rate')
    # ### end Alembic commands ###
