"""empty message

Revision ID: b8b77bef3e60
Revises: a0d565db90b5
Create Date: 2020-03-13 12:48:33.992159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b77bef3e60'
down_revision = 'a0d565db90b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generator', sa.Column('available_at_points_per_second', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generator', 'available_at_points_per_second')
    # ### end Alembic commands ###
