"""empty message

Revision ID: d31f0f2e4c54
Revises: 53d530d3c054
Create Date: 2020-03-22 12:01:51.434982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd31f0f2e4c54'
down_revision = '53d530d3c054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generator', sa.Column('order', sa.Integer(), nullable=True))
    op.add_column('upgrade', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upgrade', 'order')
    op.drop_column('generator', 'order')
    # ### end Alembic commands ###
